# Основные настройки
line-length = 88

# Настройка правил
[lint]
# E, W - ошибки и предупреждения стиля (pycodestyle)
# F - ошибки логики (pyflakes), включая F401 (неиспользуемые импорты)
# I - сортировка импортов (isort)
select = ["E", "W", "F", "I"]

[lint.isort]
# Дополнительные настройки сортировки
combine-as-imports = true