# Основные настройки
line-length = 88
target-version = "py310"

# Настройка правил
[lint]
# E, W - ошибки и предупреждения стиля (pycodestyle)
# F - ошибки логики (pyflakes), включая F401 (неиспользуемые импорты)
# I - сортировка импортов (isort)
select = ["E", "W", "F", "I"]

# Указываем, какие правила можно исправлять автоматически
fixable = ["I", "F401"]

[lint.isort]
# Дополнительные настройки сортировки
combine-as-imports = true